# You should place the proper certs on the server directly. This wont replace it.

- name: Install openssl
  package:
    name: openssl
    state: present

- name: Create self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ item }}" -days 365 -keyout {{ apache_ssl_certificate_path }}/private/{{ item }}.key -out {{ apache_ssl_certificate_path }}/certs/{{ item }}.crt -extensions v3_ca creates={{ apache_ssl_certificate_path }}/private/{{ item }}.key
  notify: restart apache
  with_items: "{{ wiki_instances }}"
