# You should place the proper certs on the server directly. This wont replace it.

- name: Install openssl
  package:
    name: openssl
    state: present

- name: Create self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ item }}" -days 365 -keyout {{ item.certificate_key_file }} -out {{ item.certificate_file }} -extensions v3_ca creates={{ item.certificate_key_file }}
  notify: restart apache
  with_items: "{{ apache_vhosts_ssl }}"
