webdomain_sanat: sanat.csc.fi
webaliases_sanat: []
webdomain_nimiarkisto: nimiarkisto.fi
webaliases_nimiarkisto: []
webdomain_termipankki: tieteentermipankki.fi
webaliases_termipankki: []


mediawikis: []

apache_ssl_protocol: "all -SSLv3"
apache_ssl_cipher_suite: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"

certificate_path: /etc/pki/tls

ssl_params_sanat:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_sanat }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_sanat }}.key"
ssl_params_nimiarkisto:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_nimiarkisto }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_nimiarkisto }}.key"
ssl_params_termipankki:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_termipankki }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_termipankki }}.key"


hfst_tmp: /tmp/hfst
hfst_url: http://apertium.projectjj.com/apt/release/pool/main/h/hfst/
hfst_bin: hfst_3.14.0-1~trusty1_amd64
hfst_lib: libhfst51_3.14.0-1~trusty1_amd64
hfst_components:
 - [ '{{ hfst_bin }}' , 'sha256:70b6bdc1f2f9489a73ef1f096feac6f3f70546e5f99288fd8afaba7207e2ea9e' ]
 - [ '{{ hfst_lib }}' , 'sha256:ad9cec6b8472d8d7568aac25cc09a4af8acbf341a06e755cf918839cf1d8b56e' ]


memcached_memory_limit: 4G
composer_keep_updated: true

nodejs_version: "7.10.0"

php_enable_php_fpm: true
sms_xml:
  wiki_username: "SyncBot"
  wiki_password: "SyncBot12"
  debug: "True"
